[package]
name = "bgm-wiki-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.8"